### PR TITLE
Give Mint all the shit he wants ty :3

### PR DESCRIPTION
**Pull request by UtopiaMint**

### CODE REVIEW

**Comment by Tr-Jono** [comment]
Thou shalt remove the tag9mint function. For thine information, the function would not work as it has not been assigned to a command. Thou shalt delete the whole goddamn function as it is designed solely for on9s and will need a whole redesign in your case. I shall merge the remaining one line change after your deletion.

**Comment by UtopiaMint** [comment]
Pull me :3

**Comment by Tr-Jono** [comment]
The PR is very constructive. It has successfully implemented complex features under the current constraints of the library. It has also managed to improve the overall speed of command processing. Very interesting.

**Comment by Tr-Jono** [comment]
It should take effect after a few minutes.

**Pull request merged**
